# Generated by Django 5.0.4 on 2024-11-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('hsn_code', models.CharField(max_length=20)),
                ('carton_quantity', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
    ]
