# Generated by Django 5.0.4 on 2024-11-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
    ]
