# Generated by Django 5.0.4 on 2024-12-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0005_remove_product_stock_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Home & Kitchen', 'Home & Kitchen'), ('Health & PersonalCare', 'Health & PersonalCare'), ('Safety Products', 'Safety Products'), ('Electronic', 'Electronic'), ('Monsoon Collection', 'Monsoon Collection'), ('Baby Products', 'Baby Products'), ('Stationaries', 'Stationaries'), ('Home Decor', 'Home Decor'), ('Packaging Material', 'Packaging Material')], default='Electronics', max_length=50),
        ),
    ]
